# Generated by Django 5.0.6 on 2024-07-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_address_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$WHHdLiHnPj74jx9KZf4HWS$6rgpqPNT6cZ7wMde7MGLHKd/ejT1eghcxNxZsEcGL8w=', max_length=255),
        ),
    ]
