# Generated by Django 5.0.6 on 2024-07-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$p0kKR46ebhqN5Ot7jgbfYc$8k3jcfhJG4g6kub8JyMJ612aLZPnwRDW7dtC8ovRwac=', max_length=255),
        ),
    ]
