# Generated by Django 5.0.6 on 2024-06-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
