# Generated by Django 5.0.6 on 2024-06-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_address_alter_userprofile_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user1',
        ),
        migrations.RenameModel(
            old_name='userprofile',
            new_name='userprofiles',
        ),
    ]
