# Generated by Django 5.0.6 on 2024-06-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_user1_rename_userprofile_userprofiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user1',
            new_name='user',
        ),
        migrations.RenameModel(
            old_name='userprofiles',
            new_name='userprofile',
        ),
    ]
