# Generated by Django 5.0.6 on 2024-06-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_user'),
        ('users', '0008_alter_userprofile_user'),
    ]

    operations = [
    ]
